# Generated by Django 2.0.1 on 2018-01-30 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DenominacionSocial', models.CharField(max_length=50, unique=True)),
                ('RFC', models.CharField(max_length=30)),
                ('Telefono', models.CharField(max_length=30)),
                ('Calle', models.CharField(max_length=50)),
                ('NumExterior', models.CharField(max_length=30)),
                ('NumInterior', models.CharField(max_length=30)),
                ('CodigoPostal', models.CharField(max_length=30)),
                ('SitioWeb', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uno', models.CharField(max_length=30)),
                ('Dos', models.CharField(max_length=30)),
                ('Tres', models.CharField(max_length=30)),
                ('Cuatro', models.CharField(max_length=30)),
                ('Cinco', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Estado', models.CharField(max_length=30)),
                ('Municipio', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Espera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empresas_idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unipymes.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Correo', models.CharField(max_length=50)),
                ('Empresa', models.CharField(max_length=50)),
                ('Asunto', models.CharField(max_length=30)),
                ('Texto', models.TextField()),
                ('Estado', models.CharField(default='Sin Responder', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Descripcion', models.TextField()),
                ('Disponible', models.IntegerField(default=0)),
                ('Convocatoria', models.ImageField(upload_to='Convocatorias')),
                ('Precio', models.CharField(max_length=30)),
                ('Carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unipymes.Carrera')),
                ('Escuela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unipymes.Escuela')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=30)),
                ('Empresas_idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unipymes.Empresa')),
                ('Servicios_idServicios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unipymes.Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('ApellidoP', models.CharField(max_length=30)),
                ('ApellidoM', models.CharField(max_length=30)),
                ('FechaNacimiento', models.DateField()),
                ('NumTelefono', models.CharField(max_length=30)),
                ('EstadoCivil', models.CharField(max_length=30)),
                ('Sexo', models.CharField(max_length=30)),
                ('Escolaridad', models.CharField(max_length=30)),
                ('Estado', models.CharField(max_length=30)),
                ('Municipio', models.CharField(max_length=30)),
                ('Domicilio', models.CharField(max_length=30)),
                ('NumExterior', models.CharField(max_length=30)),
                ('NumInterior', models.CharField(max_length=30)),
                ('CodigoPostal', models.CharField(max_length=30)),
                ('Correo', models.CharField(max_length=30)),
                ('Usuario', models.CharField(max_length=30, unique=True)),
                ('Contraseña', models.CharField(max_length=30)),
                ('Empresas_idEmpresas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unipymes.Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='solicitude',
            name='Usuarios_idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unipymes.Usuario'),
        ),
        migrations.AddField(
            model_name='espera',
            name='Servicios_idServicios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unipymes.Servicio'),
        ),
        migrations.AddField(
            model_name='espera',
            name='Usuarios_idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unipymes.Usuario'),
        ),
    ]
