# Generated by Django 2.0.7 on 2018-07-19 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaNacimiento', models.DateField(blank=True, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('EstadoCivil', models.CharField(blank=True, max_length=50, null=True)),
                ('Sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('Escolaridad', models.CharField(blank=True, max_length=50, null=True)),
                ('Estado', models.CharField(blank=True, max_length=50, null=True)),
                ('Municipio', models.CharField(blank=True, max_length=50, null=True)),
                ('Domicilio', models.CharField(blank=True, max_length=50, null=True)),
                ('NumExterior', models.CharField(blank=True, max_length=50, null=True)),
                ('NumInterior', models.CharField(blank=True, max_length=50, null=True)),
                ('CodigoPostal', models.CharField(blank=True, max_length=50, null=True)),
                ('Correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('Encargado', models.BooleanField(default=False)),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DenominacionSocial', models.CharField(max_length=50, unique=True)),
                ('RFC', models.CharField(blank=True, max_length=50, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('Calle', models.CharField(blank=True, max_length=50, null=True)),
                ('NumExterior', models.CharField(blank=True, max_length=50, null=True)),
                ('NumInterior', models.CharField(blank=True, max_length=50, null=True)),
                ('CodigoPostal', models.CharField(blank=True, max_length=50, null=True)),
                ('SitioWeb', models.CharField(blank=True, max_length=50, null=True)),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Consideracion', models.CharField(max_length=50)),
                ('Mejoras', models.CharField(max_length=50)),
                ('Calificacion_Producto', models.CharField(max_length=50)),
                ('Para_Mejorar', models.CharField(max_length=50)),
                ('Recomendacion', models.CharField(max_length=50)),
                ('Comentarios', models.TextField()),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unipymes.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Espera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unipymes.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=50)),
                ('Empresa', models.CharField(max_length=50)),
                ('Asunto', models.CharField(max_length=50)),
                ('Texto', models.TextField()),
                ('Estado', models.CharField(choices=[('Sin Responder', 'Sin Responder'), ('Respondido', 'Respondido')], default='Sin Responder', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje_Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mensaje', models.TextField()),
                ('Archivo', models.FileField(blank=True, null=True, upload_to='Mensajes')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Descripcion', models.TextField()),
                ('Disponible', models.IntegerField(default=0)),
                ('Imagen', models.ImageField(upload_to='Servicios')),
                ('Precio', models.CharField(max_length=50)),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unipymes.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(choices=[('0', 'Solicitud Enviada'), ('10', 'Solicitud Recibida'), ('20', 'Se Realizó la Primera Reunión'), ('40', 'Se Realizó la primer Revisión'), ('60', 'Se Realizó la segunda Revisión'), ('80', 'Se Realizó la tercera Revisión'), ('90', 'Se Realizó la Entrega'), ('100', 'Finalizado')], max_length=50)),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unipymes.Empresa')),
                ('Encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encargado', to=settings.AUTH_USER_MODEL)),
                ('Mensaje_Solicitud', models.ManyToManyField(blank=True, to='unipymes.Mensaje_Solicitud')),
                ('Servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unipymes.Servicio')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='espera',
            name='Servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unipymes.Servicio'),
        ),
        migrations.AddField(
            model_name='espera',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
