# Generated by Django 2.0.1 on 2018-01-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitude',
            name='Estado',
            field=models.CharField(choices=[('Solicitud Enviada', '0'), ('Solicitud Recibida', '10'), ('Se Realizó la Primera Reunión', '20'), ('Se Realizó la primer Revisión', '40'), ('Se Realizó la segunda Revisión', '60'), ('Se Realizó la tercera Revisión', '80'), ('Se Realizó la Entrega', '90'), ('Finalizado', '100')], max_length=50),
        ),
    ]
