# Generated by Django 2.0.7 on 2018-07-20 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseñas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empresa', models.CharField(max_length=50)),
                ('Empresario', models.CharField(max_length=50)),
                ('Imagen', models.ImageField(upload_to='Reseñas')),
                ('Reseña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unipymes.Empresa')),
            ],
        ),
    ]
