# Generated by Django 2.0.1 on 2018-01-16 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='Carrera',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='unipymes.Carrera'),
            preserve_default=False,
        ),
    ]
