# Generated by Django 2.0.1 on 2018-01-16 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0002_auto_20180115_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='Escuela',
        ),
        migrations.AddField(
            model_name='servicio',
            name='Escuela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unipymes.Escuela'),
        ),
    ]
