# Generated by Django 2.0.7 on 2018-07-20 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0002_reseñas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reseñas',
            new_name='Reseña',
        ),
    ]
