# Generated by Django 2.0.6 on 2018-06-25 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0002_auto_20180624_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encuesta',
            old_name='Cinco',
            new_name='Calificacion_Producto',
        ),
        migrations.RenameField(
            model_name='encuesta',
            old_name='Comentario',
            new_name='Comentarios',
        ),
        migrations.RenameField(
            model_name='encuesta',
            old_name='Cuatro',
            new_name='Consideracion',
        ),
        migrations.RenameField(
            model_name='encuesta',
            old_name='Dos',
            new_name='Mejoras',
        ),
        migrations.RenameField(
            model_name='encuesta',
            old_name='Tres',
            new_name='Para_Mejorar',
        ),
        migrations.RenameField(
            model_name='encuesta',
            old_name='Uno',
            new_name='Recomendacion',
        ),
    ]
