# Generated by Django 2.0.1 on 2018-01-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0002_auto_20180130_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='Estado',
            field=models.CharField(choices=[('Sin Responder', 'Sin Responder'), ('Respondido', 'Respondido')], default='Sin Responder', max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='Estado',
            field=models.CharField(choices=[('0', 'Solicitud Enviada'), ('10', 'Solicitud Recibida'), ('20', 'Se Realizó la Primera Reunión'), ('40', 'Se Realizó la primer Revisión'), ('60', 'Se Realizó la segunda Revisión'), ('80', 'Se Realizó la tercera Revisión'), ('90', 'Se Realizó la Entrega'), ('100', 'Finalizado')], max_length=50),
        ),
    ]
