# Generated by Django 2.0.1 on 2018-01-30 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0003_auto_20180130_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='Usuarios_idUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='unipymes.Usuario'),
            preserve_default=False,
        ),
    ]
