# Generated by Django 2.0.7 on 2018-07-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0003_auto_20180719_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='Reseña',
            field=models.TextField(),
        ),
    ]
