# Generated by Django 2.0.6 on 2018-06-30 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unipymes', '0003_auto_20180624_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje_Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mensaje', models.TextField()),
                ('Archivo', models.FileField(upload_to='Mensajes')),
            ],
        ),
        migrations.AddField(
            model_name='solicitude',
            name='Encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encargado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensaje_solicitud',
            name='Solicitude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unipymes.Solicitude'),
        ),
        migrations.AddField(
            model_name='mensaje_solicitud',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
