# Generated by Django 2.0.6 on 2018-06-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0004_auto_20180630_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje_solicitud',
            name='Solicitude',
        ),
        migrations.AddField(
            model_name='solicitude',
            name='Mensaje_Solicitud',
            field=models.ManyToManyField(to='unipymes.Mensaje_Solicitud'),
        ),
    ]
