# Generated by Django 2.0.1 on 2018-01-31 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0004_encuesta_usuarios_idusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuestasec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empresas_idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unipymes.Empresa')),
            ],
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='Usuarios_idUsuario',
        ),
        migrations.AddField(
            model_name='encuestasec',
            name='Encuestas_idEncuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unipymes.Encuesta'),
        ),
    ]
