# Generated by Django 2.1.7 on 2019-03-18 06:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0004_auto_20180719_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenPrincipal', models.ImageField(upload_to='Post')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('contenidoDetalle', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
