# Generated by Django 2.1.7 on 2019-03-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0005_comentarios_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
