# Generated by Django 2.0.1 on 2018-01-28 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0005_auto_20180128_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pregunta', models.CharField(max_length=30)),
                ('Respuesta', models.CharField(max_length=30)),
                ('Empresas_idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unipymes.Empresa')),
                ('Servicios_idServicios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unipymes.Servicio')),
                ('Usuarios_idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unipymes.Usuario')),
            ],
        ),
    ]
