# Generated by Django 2.0.6 on 2018-06-30 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0005_auto_20180630_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje_solicitud',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
