# Generated by Django 2.0.1 on 2018-01-29 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0006_encuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='Empresas_idEmpresa',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='Pregunta',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='Servicios_idServicios',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='Usuarios_idUsuario',
        ),
    ]
