# Generated by Django 2.0.1 on 2018-01-31 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0006_auto_20180130_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encuesta',
            old_name='Empresas_idEmpresa',
            new_name='Empresas_idEmpresas',
        ),
    ]
