# Generated by Django 2.0.6 on 2018-06-30 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0006_mensaje_solicitud_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje_solicitud',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
