# Generated by Django 2.0.1 on 2018-01-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0007_auto_20180128_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encuesta',
            old_name='Respuesta',
            new_name='Cinco',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='Cuatro',
            field=models.CharField(default='hola', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='Dos',
            field=models.CharField(default='hola1', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='Tres',
            field=models.CharField(default='hola3', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='Uno',
            field=models.CharField(default='hola4', max_length=30),
            preserve_default=False,
        ),
    ]
