# Generated by Django 2.0.1 on 2018-01-29 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0008_auto_20180129_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='Empresas_idEmpresa',
            field=models.ForeignKey(default='hola', on_delete=django.db.models.deletion.CASCADE, to='unipymes.Empresa'),
            preserve_default=False,
        ),
    ]
