# Generated by Django 2.0.6 on 2018-06-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0008_auto_20180630_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje_solicitud',
            name='Archivo',
            field=models.FileField(blank=True, null=True, upload_to='Mensajes'),
        ),
    ]
