# Generated by Django 2.0.1 on 2018-01-31 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0008_auto_20180131_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='Empresas_idEmpresa',
        ),
    ]
