# Generated by Django 2.0.6 on 2018-07-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0009_auto_20180630_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato',
            name='Encargado',
            field=models.BooleanField(default=False),
        ),
    ]
