# Generated by Django 2.0.6 on 2018-07-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0010_dato_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitude',
            name='Mensaje_Solicitud',
            field=models.ManyToManyField(blank=True, null=True, to='unipymes.Mensaje_Solicitud'),
        ),
    ]
