# Generated by Django 2.0.6 on 2018-07-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0011_auto_20180630_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitude',
            name='Mensaje_Solicitud',
            field=models.ManyToManyField(blank=True, to='unipymes.Mensaje_Solicitud'),
        ),
    ]
