# Generated by Django 2.0.1 on 2018-01-29 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0011_encuesta_empresas_idempresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='Empresas_idEmpresa',
        ),
    ]
