# Generated by Django 2.0.1 on 2018-02-04 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unipymes', '0012_remove_encuesta_empresas_idempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='Empresas_idEmpresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='unipymes.Empresa'),
            preserve_default=False,
        ),
    ]
